### ISSUE TITLE
V 0.0.2

### ISSUE THREAD

**Issue by maria-novas** [palatej/rjd3sa#1]
Dear Jean,
I have tried to install the last version (v 0.0.2) of this package and I couldn't, it returns this message.
> library(rjd3sa)
sa.proto:32:9:"modelling.Component" is not defined.
sa.proto:33:9:"modelling.Component" is not defined.
sa.proto:34:9:"modelling.Component" is not defined.
sa.proto:35:9:"modelling.Component" is not defined.
sa.proto:36:9:"modelling.Component" is not defined.
Error: package or namespace load failed for ‘rjd3sa’:
 .onLoad failed in loadNamespace() for 'rjd3sa', details:
  call: readProtoFiles2(protoPath = proto.dir)
  error: Could not load proto file 'sa.proto'

Thanks in advance,
María

**Comment by palatej** [comment]
Sorry. I didn't launch the right module.
A new set of packages is available (also for toolkit, tramoseats and x13)
